spring:
  redis:
    database: 2
    host: luke.host
    port: 6379
    password: beautifulworld
    timeout: 6000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    client-type: lettuce
  application:
    name: huahuo-user
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 124.221.15.123:8848
        namespace: e0b14217-92d0-4745-9ad5-86b3c9d8d6b0
  profiles:
    active: service,web
